services:
  # React Frontend
  frontend:
    build: ./claims-management-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    networks:
      - app-net

  # Node.js Backend
  backend:
    build: ./Backend
    ports:
      - "4000:4000"
    env_file:
      - .env.backend
    depends_on:
      - mongo
    networks:
      - app-net

  # MongoDB
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  # Mautic
  mautic:
    image: mautic/mautic:v4
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mauticMysql
    environment:
      - MAUTIC_DB_HOST=mauticMysql
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=secret
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
    volumes:
      - ./.storage/mautic:/var/www/html
    networks:
      - database
      - mautic

  # Mautic MySQL
  mauticMysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=mautic
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./.storage/mysql:/var/lib/mysql
    networks:
      - database

  # Mautic Mailhog
  mauticMailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - mautic

  # Elasticsearch for Unomi (moved above unomi to fix depends_on)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - app-net

  # Apache Unomi
  unomi:
    image: apache/unomi:1.5.7
    environment:
      - UNOMI_ELASTICSEARCH_ADDRESSES=elasticsearch:9200
      - UNOMI_THIRDPARTY_PROVIDER1_IPADDRESSES=0.0.0.0/0,::1,127.0.0.1
    ports:
      - 8181:8181
      - 9443:9443
      - 8102:8102
    depends_on:
      - elasticsearch
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
  database:
  mautic:
